### PR TITLE
Logging errors

### PR DESCRIPTION
**Pull request by HerasymovaV**
Added error logging for Chat Hub, EducationMaterialController, UserController, AssignmentController, AccountController.
Will be updated in future.
May not include all methods and errors as I was working with develop branch from 13.08.

### CODE REVIEW

**Review by gavrylenko-daiana — APPROVED** [review]

**Comment by HerasymovaV** [comment]
[Add logging errors for chat hub](https://trello.com/c/0Dm2ofna/81-add-logging-errors-for-chat-hub)

**Comment by HerasymovaV** [comment]
[Add logging errors for user controller](https://trello.com/c/I2WqdLSh/80-add-logging-errors-for-user-controller)

**Comment by HerasymovaV** [comment]
[Add logging errors for assignment controller](https://trello.com/c/RD35UNzv/77-add-logging-errors-for-assignment-controller)

**Comment by HerasymovaV** [comment]
[Add logging errors for account controller](https://trello.com/c/2Bz0i8gw/78-add-logging-errors-for-account-controller)

**Review by KatrinaSidorenko — APPROVED** [review]

**Pull request merged**
