### PR TITLE
Create GroupServiceTests.cs

### PR DESCRIPTION
**Pull request by darhan1168**

### CODE REVIEW

**Comment by darhan1168** [comment]
[Unit test for CreateGroup with NullGroup](https://trello.com/c/dAcFiyiC/229-unit-test-for-creategroup-with-nullgroup)

**Comment by darhan1168** [comment]
[Unit test for CalculateStudentProgressInGroup with SomeCompletedAssignments](https://trello.com/c/wSog2tHN/233-unit-test-for-calculatestudentprogressingroup-with-somecompletedassignments)

**Comment by darhan1168** [comment]
[Unit test for CalculateStudentProgressInGroup with NoCompletedAssignments](https://trello.com/c/b3przG1Z/232-unit-test-for-calculatestudentprogressingroup-with-nocompletedassignments)

**Comment by darhan1168** [comment]
[Unit test for CreateGroup with NullUser](https://trello.com/c/P3wyfQnL/230-unit-test-for-creategroup-with-nulluser)

**Comment by darhan1168** [comment]
[Unit test for CreateGroup with InvalidDateRange](https://trello.com/c/ActtWul3/231-unit-test-for-creategroup-with-invaliddaterange)

**Review by gavrylenko-daiana — APPROVED** [review]

**Review by KatrinaSidorenko — APPROVED** [review]

**Pull request merged**
