### PR TITLE
Add activities creation to all controllers

### PR DESCRIPTION
**Pull request by HerasymovaV**

### CODE REVIEW

**Review by KatrinaSidorenko — APPROVED** [review]

**Comment by HerasymovaV** [comment]
[Use activityService methods in educationalMaterialController](https://trello.com/c/iKpWSGgw/93-use-activityservice-methods-in-educationalmaterialcontroller)

**Comment by HerasymovaV** [comment]
[Use activityService methods in GroupController](https://trello.com/c/p6EzBWcB/91-use-activityservice-methods-in-groupcontroller)

**Comment by HerasymovaV** [comment]
[Use activityService methods in CourseController](https://trello.com/c/Cg1s4sx0/90-use-activityservice-methods-in-coursecontroller)

**Comment by HerasymovaV** [comment]
[Use activityService methods in AssignmentController](https://trello.com/c/C9O7RK3p/88-use-activityservice-methods-in-assignmentcontroller)

**Review by KatrinaSidorenko — APPROVED** [review]

**Review by darhan1168 — APPROVED** [review]

**Pull request merged**
