### PR TITLE
Unit test for user group service

### PR DESCRIPTION
**Pull request by darhan1168**

### CODE REVIEW

**Comment by darhan1168** [comment]
[Unit test for  UpdateProgressInUserGroups with NonExistentUserGroups](https://trello.com/c/VNZ3KMaH/223-unit-test-for-updateprogressinusergroups-with-nonexistentusergroups)

**Comment by darhan1168** [comment]
[Unit test for UpdateProgressInUserGroups with ExistentUserGroups](https://trello.com/c/k4RDST75/222-unit-test-for-updateprogressinusergroups-with-existentusergroups)

**Comment by darhan1168** [comment]
[Unit test for CreateCreateUserGroups with ValidUserGroups](https://trello.com/c/1Pm41dLC/220-unit-test-for-createcreateusergroups-with-validusergroups)

**Comment by darhan1168** [comment]
[Unit test for CreateUserGroups with InvalidUserGroups](https://trello.com/c/XGTiYrlO/221-unit-test-for-createusergroups-with-invalidusergroups)

**Review by HerasymovaV — APPROVED** [review]

**Review by KatrinaSidorenko — APPROVED** [review]

**Pull request merged**
